### ISSUE TITLE
Error when using ARM template

### ISSUE THREAD

**Issue by defazioadrian** [Azure/connectthedots#246]
When trying to deploy the Azure services using the "Deploy to Azure" button I receive an error,   When I look in Azure, I get the below error.  I was wondering if anyone else has had this issue?

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. (Code: DeploymentFailed)
The resource operation completed with terminal provisioning state 'failed'. (Code: ResourceDeploymentFailure)

furthermore, I see the following error when in Azure and looking  at the deployment operation details:

OPERATION ID1E5051EFE9DA5D7E
TRACKING IDe8e9a850-e07e-4f2d-bb91-ce270ed51b66
STATUSConflict
PROVISIONING STATEFailed
TIMESTAMP7/21/2016, 2:26:26 PM
DURATIONPT24.310762S
TYPEMicrosoft.Web/sites/extensions
RESOURCE ID/subscriptions/dbb25c0a-7a1a-49f3-a247-e1783711c5cd/resourceGroups/connectthedotspoc/providers/Microsoft.Web/sites/snowgaugepoc/extensions/MSDeploy
STATUSMESSAGE{
  "status": "failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'failed'.",
    "details": [
      {
        "code": "Failed",
        "message": "AppGallery Deploy Failed: 'Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---&amp;gt; System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.FetchAttributes(AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.IsPremiumApp()\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.CheckCanDeployIfAppIsPremium(AppGalleryPackageInfo packageInfo, Boolean&amp;amp; isPremium)\r\nRequest Information\r\nRequestID:\r\nRequestDate:Thu, 21 Jul 2016 20:26:17 GMT\r\nStatusMessage:Not Found\r\n'\r\nFailed to download package.\r\nAppGallery Deploy Failed: 'Microsoft.WindowsAzure.Storage.StorageException: Blob type of the blob reference doesn't match blob type of the blob. ---&gt; System.InvalidOperationException: Blob type of the blob reference doesn't match blob type of the blob.\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.UpdateAfterFetchAttributes(BlobAttributes blobAttributes, HttpWebResponse response, Boolean ignoreMD5)\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.&lt;&gt;c__DisplayClass14.&lt;GetBlobImpl&gt;b__11(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)\r\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.EndDownloadRangeToStream(IAsyncResult asyncResult)\r\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.EndDownloadToStream(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__d.MoveNext()\r\nRequest Information\r\nRequestID:\r\nRequestDate:Thu, 21 Jul 2016 20:26:19 GMT\r\nStatusMessage:OK\r\n'"
      }
    ]
  }
}

**Comment by MBevil** [comment]
I am experiencing the same issue when running the ARM template (see below). Is there a resolution or work around?

    "operationId": "b138eaa4-ac41-40e4-9862-6a36433680ed",
    "operationName": {
        "localizedValue": "Update website extension",
        "value": "Microsoft.Web/sites/extensions/write"
    },
    "properties": {
        "statusCode": "Conflict",
        "statusMessage": "{\"status\":\"failed\",\"error\":{\"code\":\"ResourceDeploymentFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'failed'.\",\"details\":[{\"code\":\"Failed\",\"message\":\"AppGallery Deploy Failed: 'Microsoft.WindowsAzure.Storage.StorageException: Blob type of the blob reference doesn't match blob type of the blob. ---&amp;gt; System.InvalidOperationException: Blob type of the blob reference doesn't match blob type of the blob.\\r\\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.UpdateAfterFetchAttributes(BlobAttributes blobAttributes, HttpWebResponse response, Boolean ignoreMD5)\\r\\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.&amp;lt;&amp;gt;c__DisplayClass18.&amp;lt;FetchAttributesImpl&amp;gt;b__17(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)\\r\\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)\\r\\n   --- End of inner exception stack trace ---\\r\\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)\\r\\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.FetchAttributes(AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)\\r\\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.IsPremiumApp()\\r\\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.CheckCanDeployIfAppIsPremium(AppGalleryPackageInfo packageInfo, Boolean&amp;amp; isPremium)\\r\\nRequest Information\\r\\nRequestID:\\r\\nRequestDate:Wed, 10 Aug 2016 00:59:31 GMT\\r\\nStatusMessage:OK\\r\\n'\\r\\nFailed to download package.\\r\\nAppGallery Deploy Failed: 'Microsoft.WindowsAzure.Storage.StorageException: Blob type of the blob reference doesn't match blob type of the blob. ---&gt; System.InvalidOperationException: Blob type of the blob reference doesn't match blob type of the blob.\\r\\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.UpdateAfterFetchAttributes(BlobAttributes blobAttributes, HttpWebResponse response, Boolean ignoreMD5)\\r\\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.&lt;&gt;c__DisplayClass14.&lt;GetBlobImpl&gt;b__11(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)\\r\\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)\\r\\n   --- End of inner exception stack trace ---\\r\\n   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result)\\r\\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.EndDownloadRangeToStream(IAsyncResult asyncResult)\\r\\n   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.EndDownloadToStream(IAsyncResult asyncResult)\\r\\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__6.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__d.MoveNext()\\r\\nRequest Information\\r\\nRequestID:\\r\\nRequestDate:Wed, 10 Aug 2016 00:59:31 GMT\\r\\nStatusMessage:OK\\r\\n'\"}]}}"

**Comment by defazioadrian** [comment]
Mike,

Although I haven't verified this, I believe you need to download the website solution and publish to Azure.  I haven't gotten around to trying this yet though.

**Comment by olivierbloch** [comment]
Sorry for the late answer, I was out on vacation for the last 2 weeks.
We have a bug on this one.
What's going on is that the deployment fails because for some reason ARM doesn't like the format of the webdeploy package for the website (something changed and I have not had time to figure out why just yet).
The workaround consists in deploying the website from Visual Studio (after you have deployed all the other services using the ARM template, discard the error). Open the website solution in Visual Studio, right click on the project, select deploy, and in the wizzard do a webdeploy to the already existing website that has been deployed by the ARM template. Everything will already be configured to connect the website to the other services.
 I will try and sort the ARM template issue this week. stay tuned

**Comment by olivierbloch** [comment]
I have pushed changes in the deployment template to address the issue.

**Comment by MrRodrigoAntunes** [comment]
I'm experiencing what looks to be the same issue, could anyone help?

 
17:34:27 - Template deployment returned the following errors:
17:34:27 - 17:34:20 - Resource Microsoft.Web/sites/extensions 'webSite7drc67namzjkk/MSDeploy' failed with message '{
17:34:27 -   "status": "failed",
17:34:27 -   "error": {
17:34:27 -     "code": "ResourceDeploymentFailure",
17:34:27 -     "message": "The resource operation completed with terminal provisioning state 'failed'.",
17:34:27 -     "details": [
17:34:27 -       {
17:34:27 -         "code": "Failed",
17:34:27 -         "message": "Failed to download package.\r\nAppGallery Deploy Failed: 'System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;amp;lt;Download&amp;amp;gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;amp;lt;Download&amp;amp;gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;amp;lt;DownloadPackageAndSettings&amp;amp;gt;d__21.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;amp;lt;DownloadAndDeployPackage&amp;amp;gt;d__11.MoveNext()'\r\nFailed to download package.\r\nAppGallery Deploy Failed: 'System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;lt;Download&amp;gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&amp;lt;Download&amp;gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;lt;DownloadPackageAndSettings&amp;gt;d__21.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;lt;DownloadAndDeployPackage&amp;gt;d__11.MoveNext()'\r\nFailed to download package.\r\nAppGallery Deploy Failed: 'System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__21.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__11.MoveNext()'"
17:34:27 -       }
17:34:27 -     ]
17:34:27 -   }

**Comment by lsprado** [comment]
I have the same issue

00:08:15 - Template deployment returned the following errors:
00:08:15 - 12:07:48 AM - Resource Microsoft.Web/sites/extensions 'ContosoAdsApp/MSDeploy' failed with message '{
00:08:15 -   "status": "failed",
00:08:15 -   "error": {
00:08:15 -     "code": "ResourceDeploymentFailure",
00:08:15 -     "message": "The resource operation completed with terminal provisioning state 'failed'.",
00:08:15 -     "details": [
00:08:15 -       {
00:08:15 -         "code": "Failed",
00:08:15 -         "message": "Failed to download package.\r\nAppGallery Deploy Failed: 'System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()'"
00:08:15 -       }
00:08:15 -     ]
00:08:15 -   }
00:08:15 - }'
00:08:15 - 12:07:49 AM - Failed to download package.
00:08:15 - AppGallery Deploy Failed: 'System.Net.WebException: The remote server returned an error: (404) Not Found.
00:08:15 -    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
00:08:15 -    at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
00:08:15 -    at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
00:08:15 - --- End of stack trace from previous location where exception was thrown ---
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
00:08:15 -    at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()
00:08:15 - --- End of stack trace from previous location where exception was thrown ---
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
00:08:15 -    at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()
00:08:15 - --- End of stack trace from previous location where exception was thrown ---
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
00:08:15 -    at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__27.MoveNext()
00:08:15 - --- End of stack trace from previous location where exception was thrown ---
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
00:08:15 -    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
00:08:15 -    at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()'
00:08:15 - 12:08:15 AM - Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
00:08:15 - 12:08:15 AM - Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.

**Comment by vsnboda** [comment]
Hi All.
 This issue is still exists and we are getting below error when we tried to use deployment template. I am using this template to create web site and deploy linked atrifacts. kindly help me to resolve this issue.

2018-07-31T08:56:35.1140099Z VERBOSE: 8:56:35 AM - Resource Microsoft.Web/sites/extensions 'devjsol1/MSDeploy' provisioning status is running
2018-07-31T08:56:35.1347714Z VERBOSE: 8:56:35 AM - Checking deployment status in 5 seconds
2018-07-31T08:56:40.4327129Z ##[error]8:56:40 AM - Resource Microsoft.Web/sites/extensions 'devjsol1/MSDeploy' failed with message '{
  "status": "failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'failed'.",
    "details": [
      {
        "code": "Failed",
        "message": "Failed to download package.\r\nAppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()\r\n---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---\r\n'"
      }
    ]
  }
}'
2018-07-31T08:56:40.5849637Z ##[error]8:56:40 AM - Failed to download package.
AppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()
---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---
'
2018-07-31T08:56:40.6061130Z VERBOSE: 8:56:40 AM - Checking deployment status in 5 seconds
2018-07-31T08:56:45.6669748Z ##[error]8:56:45 AM - Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
2018-07-31T08:56:45.6782203Z ##[error]8:56:45 AM - Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
2018-07-31T08:56:45.7110225Z 
2018-07-31T08:56:45.7113469Z DeploymentName          : azuredeploy-0731-0855
2018-07-31T08:56:45.7115437Z CorrelationId           : b2336f94-e5da-4cc3-862d-621076a32e4b
2018-07-31T08:56:45.7117523Z ResourceGroupName       : dev
2018-07-31T08:56:45.7118814Z ProvisioningState       : Failed
2018-07-31T08:56:45.7120111Z Timestamp               : 7/31/2018 8:56:40 AM
2018-07-31T08:56:45.7121198Z Mode                    : Incremental
2018-07-31T08:56:45.7122361Z TemplateLink            : 
2018-07-31T08:56:45.7124523Z TemplateLinkString      : 
2018-07-31T08:56:45.7126057Z DeploymentDebugLogLevel : 
2018-07-31T08:56:45.7128785Z Parameters              : {[serverFarmName, 
2018-07-31T08:56:45.7134723Z                           Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], 
2018-07-31T08:56:45.7137659Z                           [serverFarmSkuName, 
2018-07-31T08:56:45.7140473Z                           Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], [webAppName, 
2018-07-31T08:56:45.7142130Z                           Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], 
2018-07-31T08:56:45.7145007Z                           [_artifactsLocation, 
2018-07-31T08:56:45.7146452Z                           Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable]...}
2018-07-31T08:56:45.7148688Z ParametersString        : 
2018-07-31T08:56:45.7150983Z                           Name             Type                       Value     
2018-07-31T08:56:45.7152875Z                           ===============  =========================  ==========
2018-07-31T08:56:45.7156926Z                           serverFarmName   String                     devhostingplan2
2018-07-31T08:56:45.7158884Z                           serverFarmSkuName  String                     F1        
2018-07-31T08:56:45.7161518Z                           webAppName       String                     devjsol1  
2018-07-31T08:56:45.7169402Z                           _artifactsLocation  String                     
2018-07-31T08:56:45.7170793Z                           https://storagedevsol.blob.core.windows.net/storagedevsolcon
2018-07-31T08:56:45.7175925Z                           _artifactsLocationSasToken  SecureString                         
2018-07-31T08:56:45.7177481Z                           exampleAppPackageFolder  String                     ExampleApp
2018-07-31T08:56:45.7179882Z                           exampleAppPackageFileName  String                     package.zip
2018-07-31T08:56:45.7181437Z                           
2018-07-31T08:56:45.7182561Z Outputs                 : 
2018-07-31T08:56:45.7183734Z OutputsString           : 
2018-07-31T08:56:45.7194584Z 
2018-07-31T08:56:46.3186647Z 
2018-07-31T08:56:46.3337326Z Template deployment returned the following errors:
2018-07-31T08:56:46.3344020Z 8:56:40 AM - Resource Microsoft.Web/sites/extensions 'devjsol1/MSDeploy' failed with message '{
2018-07-31T08:56:46.3344986Z   "status": "failed",
2018-07-31T08:56:46.3346486Z   "error": {
2018-07-31T08:56:46.3347211Z     "code": "ResourceDeploymentFailure",
2018-07-31T08:56:46.3349504Z     "message": "The resource operation completed with terminal provisioning state 'failed'.",
2018-07-31T08:56:46.3350220Z     "details": [
2018-07-31T08:56:46.3350626Z       {
2018-07-31T08:56:46.3350872Z         "code": "Failed",
2018-07-31T08:56:46.3352913Z         "message": "Failed to download package.\r\nAppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()\r\n---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---\r\n'"
2018-07-31T08:56:46.3354624Z       }
2018-07-31T08:56:46.3356293Z     ]
2018-07-31T08:56:46.3356974Z   }
2018-07-31T08:56:46.3357858Z }'
2018-07-31T08:56:46.3358512Z 8:56:40 AM - Failed to download package.
2018-07-31T08:56:46.3359917Z AppGallery Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (404) Not Found.
2018-07-31T08:56:46.3360563Z    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2018-07-31T08:56:46.3361736Z    at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
2018-07-31T08:56:46.3362322Z    at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
2018-07-31T08:56:46.3363089Z    --- End of inner exception stack trace ---
2018-07-31T08:56:46.3363639Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2018-07-31T08:56:46.3364558Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2018-07-31T08:56:46.3365739Z    at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
2018-07-31T08:56:46.3366626Z    at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__a.MoveNext()
2018-07-31T08:56:46.3367473Z --- End of stack trace from previous location where exception was thrown ---
2018-07-31T08:56:46.3368367Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-07-31T08:56:46.3369396Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-07-31T08:56:46.3370256Z    at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__0.MoveNext()
2018-07-31T08:56:46.3370828Z --- End of stack trace from previous location where exception was thrown ---
2018-07-31T08:56:46.3371547Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-07-31T08:56:46.3372198Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-07-31T08:56:46.3372931Z    at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__26.MoveNext()
2018-07-31T08:56:46.3374343Z --- End of stack trace from previous location where exception was thrown ---
2018-07-31T08:56:46.3375143Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-07-31T08:56:46.3376442Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-07-31T08:56:46.3377349Z    at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()
2018-07-31T08:56:46.3378055Z ---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
2018-07-31T08:56:46.3378907Z    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2018-07-31T08:56:46.3379789Z    at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
2018-07-31T08:56:46.3380761Z    at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---
2018-07-31T08:56:46.3381602Z '
2018-07-31T08:56:46.3384462Z 8:56:45 AM - Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
2018-07-31T08:56:46.3387765Z 8:56:45 AM - Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
2018-07-31T08:56:46.3388774Z 
2018-07-31T08:56:46.3389952Z

**Comment by LegacyChris** [comment]
Hey, I am still experiencing this issue:

2020-04-27 10:13:40.7093805
{
  "status": "failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'failed'.",
    "details": [
      {
        "code": "Failed",
        "message": "Package deployment failed\r\nAppGallery Deploy Failed: 'System.Threading.ThreadAbortException: Thread was being aborted.\r\n
   at Microsoft.Web.Deployment.DeploymentObject.EnsureValidAttributes()\r\n
   at Microsoft.Web.Deployment.DeploymentObject.get_IsValid()\r\n
   at Microsoft.Web.Deployment.SkipInvalidSourceRuleHandler.SyncSource(DeploymentSyncContext syncContext, DeploymentObject sourceObject, Boolean&amp; proceed)\r\n
   at Microsoft.Web.Deployment.DeploymentSyncEnumerable.&lt;Create&gt;d__0.MoveNext()\r\n
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)\r\n
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)\r\n
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)\r\n
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)\r\n
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)\r\n
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)\r\n
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)\r\n
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)\r\n
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)\r\n
   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)\r\n
   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.Deploy(String deploymentSite, String siteSlotId, Boolean doNotDelete)\r\n
   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__24.MoveNext()'"
      }
    ]
  }
}
